# Setup
title:               "âš ï¸í˜„ì¬ ê³µì‚¬ ì¤‘ì¸ ë¸”ë¡œê·¸ì…ë‹ˆë‹¤."
tagline:             'by Leo'
description:         "ë„“ê³  ê¹Šê²ŒğŸ“Œ <br>ì œê°€ ì–´ë ¤ì›Œí•œ ê²ƒì€ ì œ ì„ ì—ì„œ ëë‚¼ê²Œìš”"
url:                 https://leo-moooon.github.io/
baseurl:             ''
repository:          'https://github.com/Leo-Moooon'

#Site Settings
locale:              "ko-KR"
paginate:            5
permalink:           pretty

# About/contact
author:              
  name:              "ë¬¸ì„±ìš°(Leo Moon)"
  avatar:            "assets/img/avatar.jpeg"
  bio:               ""
  location:          "Republic of Korea"
  url:               ''
  email:             "leomoon7180@gmail.com"

  links:
    - label:         "GitHub"
      icon:          "fab fa-fw fa-fithub"
      url:           "https://github.com/Leo-Moooon"

# Gems
plugins:
  - jekyll-paginate
  - jemoji

# Custom vars
version:             1.0
google_analytics_id: #UA-XXXX-Y
